// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Pose Pose;
        
        public Valve.VR.SteamVR_Action_Boolean XPress;
        
        public Valve.VR.SteamVR_Action_Boolean YPress;
        
        public Valve.VR.SteamVR_Action_Vector2 PoseJL;
        
        public Valve.VR.SteamVR_Action_Vector2 PosJR;
        
        public Valve.VR.SteamVR_Action_Boolean ZPress;
        
        public Valve.VR.SteamVR_Action_Boolean WPress;
    }
}
